// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbvirdkafrqkmljwxsau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidmlyZGthZnJxa21sand4c2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NDIwNjgsImV4cCI6MjA5MTMxODA2OH0.d85DwBZnDekpoWYFHHfjiK4AhQO0gAfIDmxqul67mJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});